/*
  Export
  Method for handling data export from our app.
*/

/*
  Import our NPM packages using the meteorhacks:npm package
  The final require, 'fs', is using the core Npm.require method to pull in the
  file system from Node.js core. We're doing this because fs is not an npm
  package that we need to load. It's already available via Meteor, we just need
  to tell Meteor to give us access to it here.
*/
var fastCsv, jsZip, xmlBuilder;

jsZip = Meteor.npmRequire('jszip');

xmlBuilder = Meteor.npmRequire('xmlbuilder');

fastCsv = Meteor.npmRequire('fast-csv');

// unique identifier to ensure that we’re pulling out only the data that we want 
// (e.g. we only want to get Bob’s data and not the data for all users). To handle this, we’ll pass Peter’s user ID (generated by Meteor) as a variable called userId
// Define our exportData method
Meteor.methods({
  exportData: function(userId) {
    var assetsFolder, exportFriendsAsCsv, exportProfileAsHtml, exportProfileAsJSON, exportProfileAsXml, getComments, getFriends, getPosts, getUser, zip;

    // Check the format of the userId. Check allows us to assert that arguments
    // to a function have the right types and structure to preven unwanted data
    // being inserted into the DB.
    check(userId, String);
    // Setup our zip instance and define folders for each type of data.
    // Note: folders are optional but nice for organization. Here, we're only
    // making one folder to demonstrate the technique.
    zip = new jsZip();
    // awesome, we now have a .zip file we can send data with!
    // let's increase usability and create a folder in this zip
    assetsFolder = zip.folder('assets');
    // now let's grab some data
    // we use .fetch() bc it will transform our MongoDB cursor into an array
    //  of object we can loop through
    getUser = Meteor.users.findOne({
      "_id": userId
    }, {
      // Note: using MongoDB's Projection
      //  which enables us to specify exactly what data we want to get out of the
      //  db (0 false, 1 true)
      fields: {
        "profile.name": 1,
        "profile.photo": 1,
        "profile.biography": 1,
        "profile.location": 1,
        "profile.career": 1
      }
    });

    getGames = Games.find({
        "createdBy": userId
      }, {
        fields: {
          "_id": 1,
          "teamId": 1,
          "gameDateTime": 1,
          "opponentName": 1,
          "fieldName": 1,
          "fieldUrl": 1,
          "homeTeam": 1,
          "leagueName": 1,
          "seasonName": 1
        }
      }).fetch();

    getTeams = Teams.find({
        "owner": userId
      }, {
        fields: {
          "_id": 1,
          "teamName": 1,
          "coachName": 1,
          "coachEmail": 1,
          "logoUrl": 1,
          "homeJerseyColor": 1,
          "awayJerseyColor": 1
        }
      }).fetch();

    getPlayers = Players.find({
        "createdBy": userId
      }, {
        fields: {
          "_id": 1,
          "teamId": 1,
          "fullName": 1,
          "jerseyNumber": 1
        }
      }).fetch();

  exportPlayersAsCsv = function() {
    /*
      Export friends as a .csv file
    */
    var csv;
    csv = fastCsv;
    return csv.writeToString(getPlayers, {
      headers: true
    }, function(error, data) {
      if (error) {
        return console.log(error);
      } else {
        return zip.file('players.csv', data);
      };
    });
  };

      exportProfileAsHtml = function() {
      var container, exportCss, exportJs, footer, head, header, htmlExportString, i, j, k, len, len1, len2, profileBody, profileSidebar, scripts, playersList, player;
      exportCss = Assets.getText("export/style.css");
      exportJs = Assets.getText("export/bootstrap.js");
      assetsFolder.file('style.css', exportCss);
      assetsFolder.file('bootstrap.js', exportJs);
      head = "<head> <title>Soccermatters | Data Export</title> <meta charset='utf-8'> <meta name='viewport' content='width=device-width, initial-scale=1'> <link rel='stylesheet' type='text/css' href='assets/style.css'> </head>";
      scripts = "<script src='https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js'></script> <script src='assets/bootstrap.js'></script>";
      header = "<html>" + head + "<body>";
      footer = scripts + "</body></html>";
      playersList = "<ul>";
      for (i = 0, len = getPlayers.length; i < len; i++) {
        player = getPlayers[i];
        playersList += "<li><img src='" + player.photo + "' class='img-responsive' alt='" + player.name + "'></li>";
      }
      playersList += "</ul>";
      profileSidebar = "<img src='" + getUser.profile.photo + "' class='profile-photo img-responsive img-rounded' alt='" + getUser.profile.photo + "' /> <div class='panel panel-default user-information'> <div class='panel-heading'>About " + getUser.profile.name + "</div> <div class='panel-body'> <div class='panel-block'> <strong>Friends</strong> " + playersList + " </div> <div class='panel-block'> <strong>Location</strong> <p>" + getUser.profile.location + "</p> </div> <div class='panel-block'> <strong>Career</strong> <p>" + getUser.profile.career + "</p> </div> </div> </div>";
      teamsContent = "";
      for (j = 0, len1 = getTeams.length; j < len1; j++) {
        team = getTeams[j];
        teamsContent += "<div class='panel panel-default'> <div class='panel-body'> " + team.teamName + " </div> <div class='panel-footer'>By <strong>" + team.coachName + "</strong> on " + team.coachEmail + "</div> </div>";
      }
      gamesContent = "";
      for (k = 0, len2 = getGames.length; k < len2; k++) {
        game = getGames[k];
        gamesContent += "<div class='panel panel-default'> <div class='panel-body'> <img class='comment-avatar' src='" + game.gameDateTime + "' alt='" + game.opponentName + "'> <div class='comment-content'> " + game.fiendName + " </div> </div> <div class='panel-footer'>By <strong>" + game.homeTeam + "</strong> on " + game.gameDateTime + "</div> </div>";
      }
      profileBody = "<h2>" + getUser.profile.name + "</h2> <p>" + getUser.profile.biography + "</p> <ul class='nav nav-tabs' role='tablist'> <li class='active'><a href='#posts' role='tab' data-toggle='tab'>Posts</a></li> <li><a href='#comments' role='tab' data-toggle='tab'>Comments</a></li> </ul> <div class='tab-content'> <div class='tab-pane active posts' id='posts'> " + teamsContent + " </div> <div class='tab-pane comments' id='comments'> " + gamesContent + " </div> </div>";
      container = "<div class='container'> <div class='row'> <div class='col-xs-12 col-sm-4'> " + profileSidebar + " </div> <div class='col-xs-12 col-sm-8'> " + profileBody + " </div> </div> </div>";
      htmlExportString = header + container + footer;
      return zip.file('index.html', htmlExportString);
    };

    exportProfileAsXml = function() {
      /*
        Export full profile (Players, Teams, Games) as a .xml file
      */
      var profile, userData, teamsData, playersData, gamesData, i, j, k,
          len, len1, len2;
      profile  = xmlBuilder.create('profile');
      userData = profile.ele('user');
      userData.ele('name',      getUser.profile.name);
      userData.ele('photo',     getUser.profile.photo);
      userData.ele('biography', getUser.profile.biography);
      userData.ele('location',  getUser.profile.location);
      userData.ele('career',    getUser.profile.career);
      teamsData = profile.ele('teams');
      for (i = 0, len = getTeams.length; i < len; i++) {
        team = getTeams[i];
        teamData = teamsData.ele('team');
        teamsData.ele('name', team.teamName);
        teamsData.ele('coach_name', team.coachName);
        teamsData.ele('coach_mail', team.coachEmail);
        teamsData.ele('logo_url', team.logoUrl);
        teamsData.ele('home_jersey_color', team.homeJerseyColor);
        teamsData.ele('away_jersey_color', team.awayJerseyColor);
      }
      playersData = profile.ele('player');
      for (j = 0, len1 = getPlayers.length; j < len1; j++) {
        player = getPlayers[j];
        playerData = playersData.ele('player');
        playersData.ele('team_id', player.teamId);
        playersData.ele('fullname', player.fullName);
        playersData.ele('jersey_number', player.jerseyNumber);
      }
      gamesData = profile.ele('game');
      for (k = 0, len2 = getGames.length; k < len2; k++) {
        game = getGames[k];
        gamesData.ele('team_id', game.teamName);
        gamesData.ele('game_date_time', game.gameDateTime);
        gamesData.ele('opponent_name', game.opponentName);
        gamesData.ele('field_name', game.fieldName);
        gamesData.ele('field_url', game.fieldUrl);
        gamesData.ele('league_name', game.homeTeam);
        gamesData.ele('season_name', game.leagueName);
        gamesData.ele('season_name', game.seasonName);
      }
      profileXmlString = profile.end({
        pretty: true
      });
      return zip.file('profile.xml', profileXmlString);
    };
    exportProfileAsJSON = function() {
      var comment, friend, i, j, k, len, len1, len2, post, profile;
      profile = {
        user: {},
        teams: [],
        games: [],
        players: []
      };
      profile.user = {
        name: getUser.profile.name,
        photo: getUser.profile.photo,
        biography: getUser.profile.biography,
        location: getUser.profile.location,
        career: getUser.profile.career
      };
      for (i = 0, len = getPlayers.length; i < len; i++) {
        player = getPlayers[i];
        profile.players.push(player);
      }
      for (j = 0, len1 = getTeams.length; j < len1; j++) {
        team = getTeams[j];
        profile.teams.push(team);
      }
      for (k = 0, len2 = getGames.length; k < len2; k++) {
        game = getGames[k];
        profile.games.push(game);
      }
      profile = JSON.stringify(profile);
      return zip.file('tester.json', profile);
    };
    exportPlayersAsCsv();
    exportProfileAsXml();
    exportProfileAsHtml();
    exportProfileAsJSON();
    return zip.generate({
      type: "base64"
    });
  }
});

